name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Enable Long Paths on Windows
        run: git config --system core.longpaths true

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'  # Use master channel
          flutter-version: 'master'  # Exact Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: build/windows/x64/runner/Release/
