name: Windows Build

on: [push, pull_request]  # Runs when code is pushed or a PR is created

jobs:
  build:
    runs-on: windows-latest  # Uses a Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Fetch your repo code

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.30.0"  # Use stable Flutter version

      - name: Enable Windows Desktop Support
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: windows-build
          path: build/windows/runner/Release/